apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  params:
    - default: app
      description: name of the deployment to be patched
      name: deployment-name
      type: string
    - default: 'https://github.com/msoares94/openshift-pipelines-hello-world-with-java.git'
      description: url of the git repo for the code of deployment
      name: git-url
      type: string
    - default: 4openshift
      description: revision to be used from repo of the code for deployment
      name: git-revision
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/demo-pipelines/app
      description: image to be build from the code
      name: IMAGE
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven
      taskRef:
        kind: ClusterTask
        name: maven
      runAfter:
        - fetch-repository
      params:
        - name: GOALS
          value:
            - -Dmaven.repo.local=$(workspaces.maven-settings.path)
            - verify
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
    - name: build-image
      params:
        - name: TLSVERIFY
          value: 'false'
        - name: IMAGE
          value: $(params.IMAGE)
      runAfter:
        - maven
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: apply-manifests
      runAfter:
        - build-image
      taskRef:
        kind: Task
        name: apply-manifests
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: update-deployment
      params:
        - name: deployment
          value: $(params.deployment-name)
        - name: IMAGE
          value: $(params.IMAGE)
      runAfter:
        - apply-manifests
      taskRef:
        kind: Task
        name: update-deployment
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: maven-settings
    - name: shared-workspace
